# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Set tag output
        id: tag
        run: echo "tag_name=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
  
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tejolote
        uses: kubernetes-sigs/release-actions/setup-tejolote@a69972745f85aab4ba5d6c681e2a0e7f73eaff2b # v0.3.0
  
      - name: Generate Provenance
        id: tejolote
        run: |
            tejolote attest --artifacts github://carabiner-dev/snappy/${{ steps.tag.outputs.tag_name }} github://carabiner-dev/snappy/"${GITHUB_RUN_ID}" --output snappy-${{ steps.tag.outputs.tag_name }}.intoto.json --sign 
  