# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: read
  
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write
      
    steps:
      - name: Setup bnd
        uses: carabiner-dev/bnd-actions/setup@HEAD

      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Install tejolote
        uses: kubernetes-sigs/release-actions/setup-tejolote@a69972745f85aab4ba5d6c681e2a0e7f73eaff2b # v0.3.0

      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@a69972745f85aab4ba5d6c681e2a0e7f73eaff2b # v0.3.0

      - name: Set tag output
        id: tag
        run: echo "tag_name=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
  
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
        id: goreleaser
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Provenance
        id: tejolote
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            tejolote attest --artifacts github://${{github.repository}}/${{ steps.tag.outputs.tag_name }} github://${{github.repository}}/"${GITHUB_RUN_ID}" --output provenance.json
            bnd statement provenance.json -o snappy-${{ steps.tag.outputs.tag_name }}.provenance.json
            gh release upload ${{ steps.tag.outputs.tag_name }} snappy-${{ steps.tag.outputs.tag_name }}.provenance.json
            bnd push ${{github.repository}} snappy-${{ steps.tag.outputs.tag_name }}.provenance.json

      - name: Generate SBOM
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          bom generate --format=json -o /tmp/snappy-${{ steps.tag.outputs.tag_name }}.spdx.json .
          gh release upload ${{ steps.tag.outputs.tag_name }} /tmp/snappy-${{ steps.tag.outputs.tag_name }}.spdx.json
          